### ISSUE TITLE
The name of the persist bookmark

### ISSUE THREAD

**Issue by kimitrois** [dedukun/bookmarks.yazi#16]
Hi there! Thanks for your time and effort. It's exactly what I want since I've moved from ranger to yazi.
But  maybe kinda point that could be improved. 
For example the directory structure looks like this:
 /aaa/bbb/ccc/ddd.txt
if I cd into the directory "bbb" and save a bookmark there, the popup 'window' (after pressing ')  will show the absolute path of the dicrectory all the way to the "ccc".     b →/aaa/bbb/ccc/ .  Can we just stop at the "bbb" level?

Just a suggestion. Thanks in advance!

**Comment by dedukun** [comment]
Hey,

Yeah I can see how that would be more intuitive, the path shown is the saved path that we use when changing directories, so when say `/aaa/bbb/ccc/` it means that we are in `/aaa/bbb` with the cursor on top of `ccc`.

Having said that I will add a way for the user to be able to choose how they want to display that path, if they want the current behavior or how you are suggesting, it might just take a couple of days because I don't have much time during the week.

**Comment by kimitrois** [comment]
It would be great if users can configure that.
Take your time~ it's FOSS
Thanks!

**Comment by dedukun** [comment]
Hey,

I've added the new option in PR #17, could you test it to make sure that it functions as you expected?

The PR has the steps on how to enable this new config in it's description.

**Comment by dedukun** [comment]
Nice, I'll merge it then.

Thanks for testing.
