### ISSUE TITLE
What about to view all bookmarks?

### ISSUE THREAD

**Issue by seriiserii825** [dedukun/bookmarks.yazi#19]
Hi, thanks for plugin.
May be to add a keymap to view all bookmarks? 
Or i can't find them in documentation?

**Comment by dedukun** [comment]
Hey,

After adding bookmarks, when you use the jump function from the plugin, which is `'` with the recommended keybindings, the bookmarks should appear with their respective key and associated path, like in the following picture:

![212101_test-A](https://github.com/dedukun/bookmarks.yazi/assets/25795432/ad9b0bb5-4c0c-4ae1-b562-15faabca80f3)

Does this not happen to you?

**Comment by VimalMollyn** [comment]
Hi! Thanks for the amazing plugin. I was wondering if there was a way to view the bookmarks one below the other in rows, rather than side by side (the default right now)

**Comment by dedukun** [comment]
When there are more than 3 options, the next ones are put in another row as shown in the next picture

![095041_test-S](https://github.com/user-attachments/assets/3852c197-28a1-41df-8409-d946ada602db)

Now if you want for it to only show the options in rows, or to start stacking in rows instead of columns this is not possible at the moment. The plugin uses the [`ya.which`](https://yazi-rs.github.io/docs/plugins/utils#ya.which) method from Yazi's plugin API to show the values, and this method doesn't has any options to change this behavior.

**Comment by VimalMollyn** [comment]
Actually, I was able to modify the `ya.which` settings to display everything in 1 column in the `theme.toml` as follows.

```
[which]
cols = 1
```

**Comment by dedukun** [comment]
Oh I didn't know about that, I only looked at the plugin API and didn't think of looking into the theme options. 

Good to know that that is available to the users, so I think that this solves your request right?

**Comment by VimalMollyn** [comment]
Yup, it does. Thanks!

**Comment by dedukun** [comment]
I'm closing this issue even though this discussion was a bit off topic about the question of the original author, but seeing that there were no more interactions with the original author in over a month, and no similar reports were raised, I don't think that this issue is relevant.
