### ISSUE TITLE
Missing the final directory when listing bookmarks

### ISSUE THREAD

**Issue by GianniBYoung** [dedukun/bookmarks.yazi#30]
Hello, I am seeing an issue with how bookmarks are being listed.

When in `~/.local/share/chezmoi` I press `mC` to save my chezmoi source directory as a bookmark.

When I try to navigate back to it by using `'` the directory is incorrectly listed as `~/.local/share/` but takes me to the correct location of `~/.local/share/chezmoi`

**Comment by dedukun** [comment]
Hey,

What's your plugin configuration? We have a option [`desc_format`](https://github.com/dedukun/bookmarks.yazi?tab=readme-ov-file#desc_format) that allows the user to select to show the full path for the bookmark, or just the parent folder (by default it shows the full path)

Also, do you have multiple bookmarks, or is your terminal small? Because if there's not enough space to display the full path, this might be shortened.

Finally, just a sanity check, you are in the lastest commit right?

**Comment by GianniBYoung** [comment]
Hi, I was unable to recreate the issue after updating to yazi .0.4.1 and reinstalling all of my plugins. 

I didn't keep track of the commit I intially reported from but was able to test on 3 different computer and on one of them the font size I was using led to the missing parts of the path I had seen.

I'm fairly sure that was also the cause of the issue I reported.
